scara_setup:
  scara_setup_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - linear
      - shoulder
      - elbow
      - wrist
      - fingerjoint

    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.02 # Override default
