scara_setup:
  linear_position_controller:
    type: effort_controllers/JointPositionController
    joint: linear
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist
    pid: {p: 100.0, i: 0.01, d: 10.0}
  fingerjoint_position_controller:
    type: effort_controllers/JointPositionController
    joint: fingerjoint
    pid: {p: 100.0, i: 0.01, d: 10.0}
