controller_list:
  - name: scara_setup/scara_setup_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - linear
      - shoulder
      - elbow
      - wrist
      - fingerjoint
